### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by AhnSeongHyun** [Plate-Project/plate#31]
Traceback (most recent call last):
  File "install.py", line 45, in <module>
    reqs = [str(ir.req) for ir in install_reqs]
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1200, in parse_requirements
    skip_regex = options.skip_requirements_regex
AttributeError: 'NoneType' object has no attribute 'skip_requirements_regex'

**Comment by AhnSeongHyun** [comment]
Do not use pip install programmatically. 
Change to 
`print("Install requirements.txt")
os.system('sudo pip install -r ./requirements.txt')
`
